image: node
stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - ugrad

  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/
      - node_modules/

test:
  stage: test
  tags:
    - ugrad

  script:
    - npm test
